# Generated by Django 2.1.1 on 2018-09-01 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likes',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='likes',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user',
            name='likes',
            field=models.ManyToManyField(to='social_network.Post'),
        ),
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
