# Generated by Django 2.1.1 on 2018-09-10 14:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0005_auto_20180909_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClearbitInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('givenName', models.CharField(blank=True, max_length=255)),
                ('familyName', models.CharField(blank=True, max_length=255)),
                ('fullName', models.CharField(blank=True, max_length=255)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('timeZone', models.CharField(blank=True, max_length=255)),
                ('utcOffset', models.CharField(blank=True, max_length=255)),
                ('get_city', models.CharField(blank=True, max_length=255)),
                ('get_state', models.CharField(blank=True, max_length=255)),
                ('get_country', models.CharField(blank=True, max_length=255)),
                ('get_lat', models.CharField(blank=True, max_length=255)),
                ('get_lng', models.CharField(blank=True, max_length=255)),
                ('bio', models.CharField(blank=True, max_length=255)),
                ('site', models.CharField(blank=True, max_length=255)),
                ('avatar', models.CharField(blank=True, max_length=255)),
                ('employment_name', models.CharField(blank=True, max_length=255)),
                ('employment_title', models.CharField(blank=True, max_length=255)),
                ('employment_role', models.CharField(blank=True, max_length=255)),
                ('employment_seniority', models.CharField(blank=True, max_length=255)),
                ('employment_domain', models.CharField(blank=True, max_length=255)),
                ('facebook_handle', models.CharField(blank=True, max_length=255)),
                ('github_handle', models.CharField(blank=True, max_length=255)),
                ('github_id', models.CharField(blank=True, max_length=255)),
                ('github_avatar', models.CharField(blank=True, max_length=255)),
                ('github_company', models.CharField(blank=True, max_length=255)),
                ('github_blog', models.CharField(blank=True, max_length=255)),
                ('github_followers', models.CharField(blank=True, max_length=255)),
                ('github_following', models.CharField(blank=True, max_length=255)),
                ('twitter_handle', models.CharField(blank=True, max_length=255)),
                ('twitter_id', models.CharField(blank=True, max_length=255)),
                ('twitter_followers', models.CharField(blank=True, max_length=255)),
                ('twitter_following', models.CharField(blank=True, max_length=255)),
                ('twitter_location', models.CharField(blank=True, max_length=255)),
                ('twitter_site', models.CharField(blank=True, max_length=255)),
                ('twitter_statuses', models.CharField(blank=True, max_length=255)),
                ('twitter_favorites', models.CharField(blank=True, max_length=255)),
                ('twitter_avatar', models.CharField(blank=True, max_length=255)),
                ('linkedin_handle', models.CharField(blank=True, max_length=255)),
                ('googleplus_handle', models.CharField(blank=True, max_length=255)),
                ('gravatar_handle', models.CharField(blank=True, max_length=255)),
                ('gravatar_urls', models.CharField(blank=True, max_length=255)),
                ('gravatar_avatar', models.CharField(blank=True, max_length=255)),
                ('gravatar_avatars', models.CharField(blank=True, max_length=255)),
                ('fuzzy', models.CharField(blank=True, max_length=255)),
                ('emailProvider', models.CharField(blank=True, max_length=255)),
                ('indexedAt', models.CharField(blank=True, max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
