# Generated by Django 2.1.1 on 2018-09-10 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0006_clearbitinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clearbitinfo',
            old_name='familyName',
            new_name='name_familyName',
        ),
        migrations.RenameField(
            model_name='clearbitinfo',
            old_name='fullName',
            new_name='name_fullName',
        ),
        migrations.RenameField(
            model_name='clearbitinfo',
            old_name='givenName',
            new_name='name_givenName',
        ),
    ]
