# Generated by Django 2.1.1 on 2018-09-10 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0008_auto_20180910_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearbitinfo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
