# Generated by Django 2.1.1 on 2018-09-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0009_auto_20180910_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearbitinfo',
            name='emailProvider',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearbitinfo',
            name='fuzzy',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearbitinfo',
            name='get_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearbitinfo',
            name='get_lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='clearbitinfo',
            name='utcOffset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
