# Generated by Django 2.1.1 on 2018-09-10 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_network', '0010_auto_20180910_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clearbitinfo',
            name='emailProvider',
            field=models.NullBooleanField(),
        ),
        migrations.AlterField(
            model_name='clearbitinfo',
            name='fuzzy',
            field=models.NullBooleanField(),
        ),
    ]
